name: Enforce 100KB size limit
on:
  pull_request
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Check only files modified by this change to see if any exceed 100K
      - name: Size check
        run:  |
          head_name=${{ github.head_ref || github.ref_name }}
          echo "HEAD NAME" $head_name
          changed=$(git diff --name-only -r ${head_name} HEAD)
          if [[ -z $changed ]]; then exit 0; fi
          too_large=$(find $changed -size +100k)
          if [[ -n $too_large ]]; then exit 1; else exit 0; fi
